grp_STRAT   = "Strategy settings"
timeInput   = input.time(timestamp("1 Aug 2024 00:00 +0000"), title="Start date", group=grp_STRAT)


profit = input.float(0.4, title="止盈", group=grp_STRAT)
lost =   input.float(0.2, title="止损", group=grp_STRAT)

timePeriod  = time >= timeInput
notInTrade  = strategy.position_size <= 0
if(longcond and timePeriod and notInTrade)
    strategy.entry("Long", strategy.long)
    strategy.exit("Exit long", "Long", limit = close * (1 + profit), stop = close * (1 - lost))
if(shortcond and timePeriod and notInTrade)
    strategy.entry("Short", strategy.short)
    strategy.exit("Exit short", "Short", limit = close * (1 - profit), stop = close * (1 + lost))


if (exitlong)
    strategy.close("Long")

if (exitshort)
    strategy.close("Short")