//@version=5
// @author LazyBear 
// List of all my indicators: https://www.tradingview.com/v/4IneGo8h/
//
indicator('Weis Wave Volume [LazyBear]', shorttitle='WWV_LB')
trendDetectionLength = input(2)
showDistributionBelowZero = input(false)
mov = close > close[1] ? 1 : close < close[1] ? -1 : 0

trend = close

trend := mov != 0 and mov != mov[1] ? mov : nz(trend[1])
isTrending = ta.rising(close, trendDetectionLength) or ta.falling(close, trendDetectionLength)  //abs(close-close[1]) >= dif

wave = close
vol = close

wave := trend != nz(wave[1]) and isTrending ? trend : nz(wave[1])
vol := wave == wave[1] ? nz(vol[1]) + volume : volume
up = wave == 1 ? vol : 0
dn = showDistributionBelowZero ? wave == 1 ? 0 : wave == -1 ? -vol : vol : wave == 1 ? 0 : vol
plot(up, style=plot.style_histogram, color=color.new(color.green, 0), linewidth=3)
plot(dn, style=plot.style_histogram, color=color.new(color.red, 0), linewidth=3)


mycolor = (wave == 1) ? color.new(color.green, 90) : color.new(color.red, 90)
bgcolor(mycolor)
